services:

  mysql:
    image: mysql:8.4
    container_name: smartfit-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  core-api:
    image: soufianebenseddiq/smartfit-core-api:latest
    container_name: smartfit-core-api
    restart: always
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://smartfit-mysql:3306/${MYSQL_DATABASE}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=10000&socketTimeout=60000
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      AI_API_URL: ${AI_API_URL}
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "sleep 15 && java -jar app.jar"]
    ports:
      - "8080:8080"
    networks:
      - backend_net
      - frontend_net

  frontend:
    image: soufianebenseddiq/smartfit-frontend:latest
    container_name: smartfit-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - frontend_net

  prometheus:
    image: prom/prometheus
    container_name: smartfit-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - frontend_net

networks:
  frontend_net:
  backend_net:

volumes:
  mysql_data: